name: Lint
description: Run linter

inputs:
  working-directory:
    description: Working directory of the linter
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: |
          npm ci
          npm run lint
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      
