name: Build and Deploy Package
on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lint
        with:
          working-directory: ./package
  
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          working-directory: ./package
    needs: lint
